coverage exclude -src C:/cygwin64/home/Raghu/Documents/AHB_memory_001/scratch_area/sim/../../../AHB_memory_001/project_area/design/rtl/cmsdk_ahb_ram_beh.v -code b -line 95 -item 1 -allfalse
coverage exclude -src C:/cygwin64/home/Raghu/Documents/AHB_memory_001/scratch_area/sim/../../../AHB_memory_001/project_area/design/rtl/cmsdk_ahb_ram_beh.v -code b -line 194 -item 2
coverage exclude -src C:/cygwin64/home/Raghu/Documents/AHB_memory_001/scratch_area/sim/../../../AHB_memory_001/project_area/design/rtl/cmsdk_ahb_ram_beh.v -code b -line 96-99
coverage exclude -src C:/cygwin64/home/Raghu/Documents/AHB_memory_001/scratch_area/sim/../../../AHB_memory_001/project_area/design/rtl/cmsdk_ahb_ram_beh.v -code e -line 205
coverage exclude -src C:/cygwin64/home/Raghu/Documents/AHB_memory_001/scratch_area/sim/../../../AHB_memory_001/project_area/design/rtl/cmsdk_ahb_ram_beh.v -code c -line 194
coverage exclude -scope /tb_top/dut -togglenode HREADYOUT -comment "HREADYOUT will be zero as reg_waitstate_cnt is 0." 
coverage exclude -scope /tb_top/dut -togglenode HRESP -comment "HRESP has been tied to zero in design" 
coverage exclude -scope /tb_top/dut/u_ahb_ram_beh -togglenode {i[0]} {i[1]} {i[2]} {i[3]} {i[4]} {i[5]} {i[6]} {i[7]} {i[8]} {i[9]} -comment "ram is initialised to zero" 
coverage exclude -scope /tb_top/dut/u_ahb_ram_beh -togglenode {i[10]} {i[11]} {i[12]} {i[13]} {i[14]} {i[15]} {i[16]} {i[17]} {i[18]} {i[19]} -comment "ram is initialised to zero" 
coverage exclude -scope /tb_top/dut/u_ahb_ram_beh -togglenode {i[20]} {i[21]} {i[22]} {i[23]} {i[24]} {i[25]} {i[26]} {i[27]} {i[28]} {i[29]} -comment "ram is initialised to zero" 
coverage exclude -scope /tb_top/dut/u_ahb_ram_beh -togglenode {i[30]} {i[31]} -comment "ram is initialised to zero" 
coverage exclude -scope /tb_top/dut/u_ahb_ram_beh -togglenode {nxt_waitstate_cnt[0]} {nxt_waitstate_cnt[1]} {nxt_waitstate_cnt[2]} {nxt_waitstate_cnt[3]} {nxt_waitstate_cnt[4]} {nxt_waitstate_cnt[5]} {nxt_waitstate_cnt[6]} {nxt_waitstate_cnt[7]} {nxt_waitstate_cnt[8]} {nxt_waitstate_cnt[9]} -comment "WS_N and WS_S - parameterrized to zero, so dependent local varibles reg_waitstatecnt and nxt_waitstate_cnt is not incrementing" 
coverage exclude -scope /tb_top/dut/u_ahb_ram_beh -togglenode {nxt_waitstate_cnt[10]} {nxt_waitstate_cnt[11]} {nxt_waitstate_cnt[12]} {nxt_waitstate_cnt[13]} {nxt_waitstate_cnt[14]} {nxt_waitstate_cnt[15]} {nxt_waitstate_cnt[16]} {nxt_waitstate_cnt[17]} {nxt_waitstate_cnt[18]} {nxt_waitstate_cnt[19]} -comment "WS_N and WS_S - parameterrized to zero, so dependent local varibles reg_waitstatecnt and nxt_waitstate_cnt is not incrementing" 
coverage exclude -scope /tb_top/dut/u_ahb_ram_beh -togglenode {nxt_waitstate_cnt[20]} {nxt_waitstate_cnt[21]} {nxt_waitstate_cnt[22]} {nxt_waitstate_cnt[23]} {nxt_waitstate_cnt[24]} {nxt_waitstate_cnt[25]} {nxt_waitstate_cnt[26]} {nxt_waitstate_cnt[27]} {nxt_waitstate_cnt[28]} {nxt_waitstate_cnt[29]} -comment "WS_N and WS_S - parameterrized to zero, so dependent local varibles reg_waitstatecnt and nxt_waitstate_cnt is not incrementing" 
coverage exclude -scope /tb_top/dut/u_ahb_ram_beh -togglenode {nxt_waitstate_cnt[30]} {nxt_waitstate_cnt[31]} -comment "WS_N and WS_S - parameterrized to zero, so dependent local varibles reg_waitstatecnt and nxt_waitstate_cnt is not incrementing" 
coverage exclude -scope /tb_top/dut/u_ahb_ram_beh -togglenode {nxt_word_addr[0]} {nxt_word_addr[1]} -comment "nxt_word_addr[1:0] has been hardcoded to zero in design" 
coverage exclude -scope /tb_top/dut/u_ahb_ram_beh -togglenode {reg_waitstate_cnt[0]} {reg_waitstate_cnt[1]} {reg_waitstate_cnt[2]} {reg_waitstate_cnt[3]} {reg_waitstate_cnt[4]} {reg_waitstate_cnt[5]} {reg_waitstate_cnt[6]} {reg_waitstate_cnt[7]} {reg_waitstate_cnt[8]} {reg_waitstate_cnt[9]} -comment "WS_N and WS_S - parameterrized to zero, so dependent local varibles reg_waitstatecnt and nxt_waitstate_cnt is not incrementing" 
coverage exclude -scope /tb_top/dut/u_ahb_ram_beh -togglenode {reg_waitstate_cnt[10]} {reg_waitstate_cnt[11]} {reg_waitstate_cnt[12]} {reg_waitstate_cnt[13]} {reg_waitstate_cnt[14]} {reg_waitstate_cnt[15]} {reg_waitstate_cnt[16]} {reg_waitstate_cnt[17]} {reg_waitstate_cnt[18]} {reg_waitstate_cnt[19]} -comment "WS_N and WS_S - parameterrized to zero, so dependent local varibles reg_waitstatecnt and nxt_waitstate_cnt is not incrementing" 
coverage exclude -scope /tb_top/dut/u_ahb_ram_beh -togglenode {reg_waitstate_cnt[20]} {reg_waitstate_cnt[21]} {reg_waitstate_cnt[22]} {reg_waitstate_cnt[23]} {reg_waitstate_cnt[24]} {reg_waitstate_cnt[25]} {reg_waitstate_cnt[26]} {reg_waitstate_cnt[27]} {reg_waitstate_cnt[28]} {reg_waitstate_cnt[29]} -comment "WS_N and WS_S - parameterrized to zero, so dependent local varibles reg_waitstatecnt and nxt_waitstate_cnt is not incrementing" 
coverage exclude -scope /tb_top/dut/u_ahb_ram_beh -togglenode {reg_waitstate_cnt[30]} {reg_waitstate_cnt[31]} -comment "WS_N and WS_S - parameterrized to zero, so dependent local varibles reg_waitstatecnt and nxt_waitstate_cnt is not incrementing" 
coverage exclude -scope /tb_top/dut/u_ahb_ram_beh -togglenode {word_addr[0]} {word_addr[1]} -comment "word_addr[1:0] has been tied to zero in design." 
