coverage exclude -scope /tb_top/dut -togglenode HRESP -comment "HRESP has been tied to zero in design" 
coverage exclude -scope /tb_top/dut/u_ahb_ram_beh -togglenode {i[0]} {i[1]} {i[2]} {i[3]} {i[4]} {i[5]} {i[6]} {i[7]} {i[8]} {i[9]}
coverage exclude -scope /tb_top/dut/u_ahb_ram_beh -togglenode {i[10]} {i[11]} {i[12]} {i[13]} {i[14]} {i[15]} {i[16]} {i[17]} {i[18]} {i[19]}
coverage exclude -scope /tb_top/dut/u_ahb_ram_beh -togglenode {i[20]} {i[21]} {i[22]} {i[23]} {i[24]} {i[25]} {i[26]} {i[27]} {i[28]} {i[29]}
coverage exclude -scope /tb_top/dut/u_ahb_ram_beh -togglenode {i[30]} {i[31]} -comment "nxt_word_addr[1:0] has been tied to zero in design." 
coverage exclude -scope /tb_top/dut/u_ahb_ram_beh -togglenode {nxt_waitstate_cnt[3]} {nxt_waitstate_cnt[4]} {nxt_waitstate_cnt[5]} {nxt_waitstate_cnt[6]} {nxt_waitstate_cnt[7]} {nxt_waitstate_cnt[8]} {nxt_waitstate_cnt[9]} {nxt_waitstate_cnt[10]} {nxt_waitstate_cnt[11]} {nxt_waitstate_cnt[12]}
coverage exclude -scope /tb_top/dut/u_ahb_ram_beh -togglenode {nxt_waitstate_cnt[13]} {nxt_waitstate_cnt[14]} {nxt_waitstate_cnt[15]} {nxt_waitstate_cnt[16]} {nxt_waitstate_cnt[17]} {nxt_waitstate_cnt[18]} {nxt_waitstate_cnt[19]} {nxt_waitstate_cnt[20]} {nxt_waitstate_cnt[21]} {nxt_waitstate_cnt[22]}
coverage exclude -scope /tb_top/dut/u_ahb_ram_beh -togglenode {nxt_waitstate_cnt[23]} {nxt_waitstate_cnt[24]} {nxt_waitstate_cnt[25]} {nxt_waitstate_cnt[26]} {nxt_waitstate_cnt[27]} {nxt_waitstate_cnt[28]} {nxt_waitstate_cnt[29]} {nxt_waitstate_cnt[30]} {nxt_waitstate_cnt[31]} {nxt_word_addr[0]} -comment "nxt_word_addr[1:0] has been tied to zero in design." 
coverage exclude -scope /tb_top/dut/u_ahb_ram_beh -togglenode {nxt_word_addr[1]} -comment "nxt_word_addr[1:0] has been tied to zero in design." 
coverage exclude -scope /tb_top/dut/u_ahb_ram_beh -togglenode {reg_waitstate_cnt[3]} {reg_waitstate_cnt[4]} {reg_waitstate_cnt[5]} {reg_waitstate_cnt[6]} {reg_waitstate_cnt[7]} {reg_waitstate_cnt[8]} {reg_waitstate_cnt[9]} {reg_waitstate_cnt[10]} {reg_waitstate_cnt[11]} {reg_waitstate_cnt[12]}
coverage exclude -scope /tb_top/dut/u_ahb_ram_beh -togglenode {reg_waitstate_cnt[13]} {reg_waitstate_cnt[14]} {reg_waitstate_cnt[15]} {reg_waitstate_cnt[16]} {reg_waitstate_cnt[17]} {reg_waitstate_cnt[18]} {reg_waitstate_cnt[19]} {reg_waitstate_cnt[20]} {reg_waitstate_cnt[21]} {reg_waitstate_cnt[22]}
coverage exclude -scope /tb_top/dut/u_ahb_ram_beh -togglenode {reg_waitstate_cnt[23]} {reg_waitstate_cnt[24]} {reg_waitstate_cnt[25]} {reg_waitstate_cnt[26]} {reg_waitstate_cnt[27]} {reg_waitstate_cnt[28]} {reg_waitstate_cnt[29]} {reg_waitstate_cnt[30]} {reg_waitstate_cnt[31]} {word_addr[0]} -comment "word_addr[1:0] has been tied to zero in design." 
coverage exclude -scope /tb_top/dut/u_ahb_ram_beh -togglenode {word_addr[1]} -comment "word_addr[1:0] has been tied to zero in design." 
